apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: harsha12101503/myapp:v2
        ports:
        - containerPort: 5000
        envFrom:
        - secretRef:
            name: postgres-secret   # DB credentials
        - secretRef:
            name: s3-secret         # S3 credentials
        readinessProbe:
          httpGet:
            path: /up
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /up
            port: 5000
          initialDelaySeconds: 15
          periodSeconds: 20
---
apiVersion: v1
kind: Service
metadata:
  name: flask-service
spec:
  selector:
    app: flask
  ports:
    - port: 80
      targetPort: 5000
  type: ClusterIP

