apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: flask
  template:
    metadata:
      labels:
        app: flask
    spec:
      containers:
      - name: flask
        image: <your-dockerhub-username>/flask-app:latest
        ports:
        - containerPort: 5000
        env:
        - name: S3_BUCKET
          value: "my-eks-flask-bucket"
        - name: POSTGRES_HOST
          value: "postgres"
        - name: POSTGRES_DB
          value: "postgres"
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        # Health checks
        livenessProbe:
          httpGet:
            path: /up
            port: 5000
          initialDelaySeconds: 10
          periodSeconds: 15
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /up
            port: 5000
          initialDelaySeconds: 5
          periodSeconds: 10
          failureThreshold: 3