apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  POSTGRES_USER: <replace-with-username>
  POSTGRES_PASSWORD: <replace-with-password>
  POSTGRES_DB: <replace-with-database>

